---
title: "On The Quality and Quantity of Girls"
subtitle: "insert subtitle"
author: 
  - Jueun Kang
  - Joyce Xuan
  - Tayedza Chikumbirike
thanks: "Code and data are available at: Insert link."
date: "`r Sys.time()`"
date-format: "D MMMM YYYY"
abstract: "insert abstract"
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(ggplot2)
library(haven)
library(janitor)
library(tidyr)
library(dplyr)
```

```{r}
clean_data <- read_csv(here::here("inputs/data/clean_data.csv"))

clean_data |>
  ggplot(aes(x = year)) +
  geom_line(aes(y = ultrasound_birth, color = "Births with Ultrasound")) +
  geom_line(aes(y = changed_column, color = "Imported Machines"), lty=2, lwd=1) +
  scale_y_continuous(
    name = "Fraction of Births with Ultrasound Use",
    sec.axis = sec_axis( ~.*1, name = "Imported Ultrasound Machines")
  ) +
  theme_minimal() +
  labs(x = "Year",
       title = "Ultrasound Use by Mothers vs. Supply of Ultrasound Scanners in India.")+
  scale_color_manual(name = "Legend", values = c("Births with Ultrasound" = "blue", "Imported Machines" = "red")) + 
  theme(legend.key.size = unit(0.3, 'cm')) +
  theme(legend.position="bottom")
```

```{r}
clean_data_2 <- read_csv(here::here("inputs/data/clean_data_2.csv"))

clean_data_2 |>
  ggplot(aes(x = yearc)) +
  geom_line(aes(y = sum_first_girl/sum_total), color = "blue") +
  xlim(1975, 2005) +
  theme_minimal() +
  labs(x = "Year",
       y = "Fraction of First Born Girls",
       title = "The evolution of the percentage of females among first births over time.")
```

```{r}
clean_data_3 <- read_csv(here::here("inputs/data/clean_data_3.csv"))

clean_data_3  |>
  ggplot(aes(x = yearc, y = sum_second_girl)) +
  geom_line(color = "red") +
  xlim(1975, 2005) +
  theme_minimal() +
  labs(x = "Year",
       y = "Number of second children who are girls",
       title = "Second Children who are girls given that the First Child was a girl")
```
